// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: proto/comment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgKind int32

const (
	// user comment
	MsgKind_OK        MsgKind = 0
	MsgKind_HeartBeat MsgKind = 1
)

// Enum value maps for MsgKind.
var (
	MsgKind_name = map[int32]string{
		0: "OK",
		1: "HeartBeat",
	}
	MsgKind_value = map[string]int32{
		"OK":        0,
		"HeartBeat": 1,
	}
)

func (x MsgKind) Enum() *MsgKind {
	p := new(MsgKind)
	*p = x
	return p
}

func (x MsgKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_comment_proto_enumTypes[0].Descriptor()
}

func (MsgKind) Type() protoreflect.EnumType {
	return &file_proto_comment_proto_enumTypes[0]
}

func (x MsgKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgKind.Descriptor instead.
func (MsgKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{0}
}

type ConnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Groups []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *ConnReq) Reset() {
	*x = ConnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnReq) ProtoMessage() {}

func (x *ConnReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnReq.ProtoReflect.Descriptor instead.
func (*ConnReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{0}
}

func (x *ConnReq) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ConnRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msgs []*Msg `protobuf:"bytes,1,rep,name=msgs,proto3" json:"msgs,omitempty"`
}

func (x *ConnRsp) Reset() {
	*x = ConnRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnRsp) ProtoMessage() {}

func (x *ConnRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnRsp.ProtoReflect.Descriptor instead.
func (*ConnRsp) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{1}
}

func (x *ConnRsp) GetMsgs() []*Msg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type PubMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *Msg `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PubMsgReq) Reset() {
	*x = PubMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubMsgReq) ProtoMessage() {}

func (x *PubMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubMsgReq.ProtoReflect.Descriptor instead.
func (*PubMsgReq) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{2}
}

func (x *PubMsgReq) GetMsg() *Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

type PubMsgRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PubMsgRsp) Reset() {
	*x = PubMsgRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubMsgRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubMsgRsp) ProtoMessage() {}

func (x *PubMsgRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubMsgRsp.ProtoReflect.Descriptor instead.
func (*PubMsgRsp) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{3}
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Gid string `protobuf:"bytes,2,opt,name=gid,proto3" json:"gid,omitempty"`
	// reply msg id
	Pid       string  `protobuf:"bytes,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Kind      MsgKind `protobuf:"varint,4,opt,name=kind,proto3,enum=proto.MsgKind" json:"kind,omitempty"` // heartbeat
	Content   string  `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp int64   `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Seq       string  `protobuf:"bytes,7,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{4}
}

func (x *Msg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Msg) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *Msg) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *Msg) GetKind() MsgKind {
	if x != nil {
		return x.Kind
	}
	return MsgKind_OK
}

func (x *Msg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Msg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Msg) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

type Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// group id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// already received message seq
	Seq string `protobuf:"bytes,2,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *Group) Reset() {
	*x = Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_comment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{5}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetSeq() string {
	if x != nil {
		return x.Seq
	}
	return ""
}

var File_proto_comment_proto protoreflect.FileDescriptor

var file_proto_comment_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x29, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x04, 0x6d, 0x73, 0x67, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x73, 0x67, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x29, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x0b, 0x0a, 0x09, 0x50, 0x75, 0x62, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70,
	0x22, 0xa7, 0x01, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x22, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4d, 0x73, 0x67, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x71, 0x22, 0x29, 0x0a, 0x05, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x65, 0x71, 0x2a, 0x20, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x42, 0x65, 0x61, 0x74, 0x10, 0x01, 0x32, 0x5e, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12,
	0x28, 0x0a, 0x04, 0x43, 0x6f, 0x6e, 0x6e, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x52, 0x73, 0x70, 0x30, 0x01, 0x12, 0x2c, 0x0a, 0x06, 0x50, 0x75, 0x62,
	0x4d, 0x73, 0x67, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x62, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75,
	0x62, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x69, 0x73, 0x68, 0x69, 0x6f, 0x6f, 0x6e, 0x2f, 0x63,
	0x6f, 0x6d, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_comment_proto_rawDescOnce sync.Once
	file_proto_comment_proto_rawDescData = file_proto_comment_proto_rawDesc
)

func file_proto_comment_proto_rawDescGZIP() []byte {
	file_proto_comment_proto_rawDescOnce.Do(func() {
		file_proto_comment_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_comment_proto_rawDescData)
	})
	return file_proto_comment_proto_rawDescData
}

var file_proto_comment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_comment_proto_goTypes = []interface{}{
	(MsgKind)(0),      // 0: proto.MsgKind
	(*ConnReq)(nil),   // 1: proto.ConnReq
	(*ConnRsp)(nil),   // 2: proto.ConnRsp
	(*PubMsgReq)(nil), // 3: proto.PubMsgReq
	(*PubMsgRsp)(nil), // 4: proto.PubMsgRsp
	(*Msg)(nil),       // 5: proto.Msg
	(*Group)(nil),     // 6: proto.Group
}
var file_proto_comment_proto_depIdxs = []int32{
	6, // 0: proto.ConnReq.groups:type_name -> proto.Group
	5, // 1: proto.ConnRsp.msgs:type_name -> proto.Msg
	5, // 2: proto.PubMsgReq.msg:type_name -> proto.Msg
	0, // 3: proto.Msg.kind:type_name -> proto.MsgKind
	1, // 4: proto.Chat.Conn:input_type -> proto.ConnReq
	3, // 5: proto.Chat.PubMsg:input_type -> proto.PubMsgReq
	2, // 6: proto.Chat.Conn:output_type -> proto.ConnRsp
	4, // 7: proto.Chat.PubMsg:output_type -> proto.PubMsgRsp
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_comment_proto_init() }
func file_proto_comment_proto_init() {
	if File_proto_comment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_comment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubMsgRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_comment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_comment_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_comment_proto_goTypes,
		DependencyIndexes: file_proto_comment_proto_depIdxs,
		EnumInfos:         file_proto_comment_proto_enumTypes,
		MessageInfos:      file_proto_comment_proto_msgTypes,
	}.Build()
	File_proto_comment_proto = out.File
	file_proto_comment_proto_rawDesc = nil
	file_proto_comment_proto_goTypes = nil
	file_proto_comment_proto_depIdxs = nil
}
